// Generated by gencpp from file android_app_communication/androidLogMsg.msg
// DO NOT EDIT!


#ifndef ANDROID_APP_COMMUNICATION_MESSAGE_ANDROIDLOGMSG_H
#define ANDROID_APP_COMMUNICATION_MESSAGE_ANDROIDLOGMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace android_app_communication
{
template <class ContainerAllocator>
struct androidLogMsg_
{
  typedef androidLogMsg_<ContainerAllocator> Type;

  androidLogMsg_()
    : message()  {
    }
  androidLogMsg_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::android_app_communication::androidLogMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::android_app_communication::androidLogMsg_<ContainerAllocator> const> ConstPtr;

}; // struct androidLogMsg_

typedef ::android_app_communication::androidLogMsg_<std::allocator<void> > androidLogMsg;

typedef boost::shared_ptr< ::android_app_communication::androidLogMsg > androidLogMsgPtr;
typedef boost::shared_ptr< ::android_app_communication::androidLogMsg const> androidLogMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::android_app_communication::androidLogMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::android_app_communication::androidLogMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace android_app_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'android_app_communication': ['/home/sz/omniWheelCareRobot/rosCode/src/android_communication/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::android_app_communication::androidLogMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::android_app_communication::androidLogMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::android_app_communication::androidLogMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::android_app_communication::androidLogMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::android_app_communication::androidLogMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::android_app_communication::androidLogMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::android_app_communication::androidLogMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::android_app_communication::androidLogMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::android_app_communication::androidLogMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "android_app_communication/androidLogMsg";
  }

  static const char* value(const ::android_app_communication::androidLogMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::android_app_communication::androidLogMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n\
";
  }

  static const char* value(const ::android_app_communication::androidLogMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::android_app_communication::androidLogMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct androidLogMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::android_app_communication::androidLogMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::android_app_communication::androidLogMsg_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANDROID_APP_COMMUNICATION_MESSAGE_ANDROIDLOGMSG_H
