// Generated by gencpp from file ros_arduino_msgs/AlarmWrite.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_ALARMWRITE_H
#define ROS_ARDUINO_MSGS_MESSAGE_ALARMWRITE_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/AlarmWriteRequest.h>
#include <ros_arduino_msgs/AlarmWriteResponse.h>


namespace ros_arduino_msgs
{

struct AlarmWrite
{

typedef AlarmWriteRequest Request;
typedef AlarmWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AlarmWrite
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::AlarmWrite > {
  static const char* value()
  {
    return "e4da51e86d3bac963ee2bb1f41031407";
  }

  static const char* value(const ::ros_arduino_msgs::AlarmWrite&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::AlarmWrite > {
  static const char* value()
  {
    return "ros_arduino_msgs/AlarmWrite";
  }

  static const char* value(const ::ros_arduino_msgs::AlarmWrite&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::AlarmWriteRequest> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::AlarmWrite > 
template<>
struct MD5Sum< ::ros_arduino_msgs::AlarmWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::AlarmWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AlarmWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::AlarmWriteRequest> should match 
// service_traits::DataType< ::ros_arduino_msgs::AlarmWrite > 
template<>
struct DataType< ::ros_arduino_msgs::AlarmWriteRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::AlarmWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AlarmWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::AlarmWriteResponse> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::AlarmWrite > 
template<>
struct MD5Sum< ::ros_arduino_msgs::AlarmWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::AlarmWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AlarmWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::AlarmWriteResponse> should match 
// service_traits::DataType< ::ros_arduino_msgs::AlarmWrite > 
template<>
struct DataType< ::ros_arduino_msgs::AlarmWriteResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::AlarmWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AlarmWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_ALARMWRITE_H
