// Generated by gencpp from file ros_arduino_msgs/LightShow.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_LIGHTSHOW_H
#define ROS_ARDUINO_MSGS_MESSAGE_LIGHTSHOW_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/LightShowRequest.h>
#include <ros_arduino_msgs/LightShowResponse.h>


namespace ros_arduino_msgs
{

struct LightShow
{

typedef LightShowRequest Request;
typedef LightShowResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LightShow
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::LightShow > {
  static const char* value()
  {
    return "e4da51e86d3bac963ee2bb1f41031407";
  }

  static const char* value(const ::ros_arduino_msgs::LightShow&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::LightShow > {
  static const char* value()
  {
    return "ros_arduino_msgs/LightShow";
  }

  static const char* value(const ::ros_arduino_msgs::LightShow&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::LightShowRequest> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::LightShow > 
template<>
struct MD5Sum< ::ros_arduino_msgs::LightShowRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::LightShow >::value();
  }
  static const char* value(const ::ros_arduino_msgs::LightShowRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::LightShowRequest> should match 
// service_traits::DataType< ::ros_arduino_msgs::LightShow > 
template<>
struct DataType< ::ros_arduino_msgs::LightShowRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::LightShow >::value();
  }
  static const char* value(const ::ros_arduino_msgs::LightShowRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::LightShowResponse> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::LightShow > 
template<>
struct MD5Sum< ::ros_arduino_msgs::LightShowResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::LightShow >::value();
  }
  static const char* value(const ::ros_arduino_msgs::LightShowResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::LightShowResponse> should match 
// service_traits::DataType< ::ros_arduino_msgs::LightShow > 
template<>
struct DataType< ::ros_arduino_msgs::LightShowResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::LightShow >::value();
  }
  static const char* value(const ::ros_arduino_msgs::LightShowResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_LIGHTSHOW_H
