// Generated by gencpp from file carebot_msgs/SetFollowState.msg
// DO NOT EDIT!


#ifndef CAREBOT_MSGS_MESSAGE_SETFOLLOWSTATE_H
#define CAREBOT_MSGS_MESSAGE_SETFOLLOWSTATE_H

#include <ros/service_traits.h>


#include <carebot_msgs/SetFollowStateRequest.h>
#include <carebot_msgs/SetFollowStateResponse.h>


namespace carebot_msgs
{

struct SetFollowState
{

typedef SetFollowStateRequest Request;
typedef SetFollowStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFollowState
} // namespace carebot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carebot_msgs::SetFollowState > {
  static const char* value()
  {
    return "6095eaec0ed61c547340fdc2200c8372";
  }

  static const char* value(const ::carebot_msgs::SetFollowState&) { return value(); }
};

template<>
struct DataType< ::carebot_msgs::SetFollowState > {
  static const char* value()
  {
    return "carebot_msgs/SetFollowState";
  }

  static const char* value(const ::carebot_msgs::SetFollowState&) { return value(); }
};


// service_traits::MD5Sum< ::carebot_msgs::SetFollowStateRequest> should match 
// service_traits::MD5Sum< ::carebot_msgs::SetFollowState > 
template<>
struct MD5Sum< ::carebot_msgs::SetFollowStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carebot_msgs::SetFollowState >::value();
  }
  static const char* value(const ::carebot_msgs::SetFollowStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carebot_msgs::SetFollowStateRequest> should match 
// service_traits::DataType< ::carebot_msgs::SetFollowState > 
template<>
struct DataType< ::carebot_msgs::SetFollowStateRequest>
{
  static const char* value()
  {
    return DataType< ::carebot_msgs::SetFollowState >::value();
  }
  static const char* value(const ::carebot_msgs::SetFollowStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carebot_msgs::SetFollowStateResponse> should match 
// service_traits::MD5Sum< ::carebot_msgs::SetFollowState > 
template<>
struct MD5Sum< ::carebot_msgs::SetFollowStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carebot_msgs::SetFollowState >::value();
  }
  static const char* value(const ::carebot_msgs::SetFollowStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carebot_msgs::SetFollowStateResponse> should match 
// service_traits::DataType< ::carebot_msgs::SetFollowState > 
template<>
struct DataType< ::carebot_msgs::SetFollowStateResponse>
{
  static const char* value()
  {
    return DataType< ::carebot_msgs::SetFollowState >::value();
  }
  static const char* value(const ::carebot_msgs::SetFollowStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAREBOT_MSGS_MESSAGE_SETFOLLOWSTATE_H
