// Generated by gencpp from file carebot_msgs/TakePanorama.msg
// DO NOT EDIT!


#ifndef CAREBOT_MSGS_MESSAGE_TAKEPANORAMA_H
#define CAREBOT_MSGS_MESSAGE_TAKEPANORAMA_H

#include <ros/service_traits.h>


#include <carebot_msgs/TakePanoramaRequest.h>
#include <carebot_msgs/TakePanoramaResponse.h>


namespace carebot_msgs
{

struct TakePanorama
{

typedef TakePanoramaRequest Request;
typedef TakePanoramaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakePanorama
} // namespace carebot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carebot_msgs::TakePanorama > {
  static const char* value()
  {
    return "ae9e615a5f5b5081544bd9259c9e0f4e";
  }

  static const char* value(const ::carebot_msgs::TakePanorama&) { return value(); }
};

template<>
struct DataType< ::carebot_msgs::TakePanorama > {
  static const char* value()
  {
    return "carebot_msgs/TakePanorama";
  }

  static const char* value(const ::carebot_msgs::TakePanorama&) { return value(); }
};


// service_traits::MD5Sum< ::carebot_msgs::TakePanoramaRequest> should match 
// service_traits::MD5Sum< ::carebot_msgs::TakePanorama > 
template<>
struct MD5Sum< ::carebot_msgs::TakePanoramaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carebot_msgs::TakePanorama >::value();
  }
  static const char* value(const ::carebot_msgs::TakePanoramaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carebot_msgs::TakePanoramaRequest> should match 
// service_traits::DataType< ::carebot_msgs::TakePanorama > 
template<>
struct DataType< ::carebot_msgs::TakePanoramaRequest>
{
  static const char* value()
  {
    return DataType< ::carebot_msgs::TakePanorama >::value();
  }
  static const char* value(const ::carebot_msgs::TakePanoramaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carebot_msgs::TakePanoramaResponse> should match 
// service_traits::MD5Sum< ::carebot_msgs::TakePanorama > 
template<>
struct MD5Sum< ::carebot_msgs::TakePanoramaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carebot_msgs::TakePanorama >::value();
  }
  static const char* value(const ::carebot_msgs::TakePanoramaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carebot_msgs::TakePanoramaResponse> should match 
// service_traits::DataType< ::carebot_msgs::TakePanorama > 
template<>
struct DataType< ::carebot_msgs::TakePanoramaResponse>
{
  static const char* value()
  {
    return DataType< ::carebot_msgs::TakePanorama >::value();
  }
  static const char* value(const ::carebot_msgs::TakePanoramaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAREBOT_MSGS_MESSAGE_TAKEPANORAMA_H
